// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReadyPlayerOne.Models;

#nullable disable

namespace ReadyPlayerOne.Migrations
{
    [DbContext(typeof(PlayerContext))]
    [Migration("20240501000223_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReadyPlayerOne.Models.Alignment", b =>
                {
                    b.Property<string>("AlignmentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AlignmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlignmentID");

                    b.ToTable("Alignments");

                    b.HasData(
                        new
                        {
                            AlignmentID = "1",
                            AlignmentType = "Lawful Good"
                        },
                        new
                        {
                            AlignmentID = "2",
                            AlignmentType = "Neutral Good"
                        },
                        new
                        {
                            AlignmentID = "3",
                            AlignmentType = "Chaotic Good"
                        },
                        new
                        {
                            AlignmentID = "4",
                            AlignmentType = "Lawful Neutral"
                        },
                        new
                        {
                            AlignmentID = "5",
                            AlignmentType = "True Neutral"
                        },
                        new
                        {
                            AlignmentID = "6",
                            AlignmentType = "Chaotic Neutral"
                        },
                        new
                        {
                            AlignmentID = "7",
                            AlignmentType = "Lawful Evil"
                        },
                        new
                        {
                            AlignmentID = "8",
                            AlignmentType = "Neutral Evil"
                        },
                        new
                        {
                            AlignmentID = "9",
                            AlignmentType = "Chaotic Evil"
                        });
                });

            modelBuilder.Entity("ReadyPlayerOne.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerID"));

                    b.Property<string>("AlignmentID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Intelligence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Luck")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerImageID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stamina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stealth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerID");

                    b.HasIndex("AlignmentID");

                    b.HasIndex("PlayerImageID");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerID = 1,
                            AlignmentID = "3",
                            Class = "Mage",
                            Health = "3",
                            Intelligence = "9",
                            Luck = "3",
                            PlayerImageID = "3",
                            PlayerName = "Esther Ulrick",
                            Stamina = "3",
                            Stealth = "6",
                            Strength = "3"
                        },
                        new
                        {
                            PlayerID = 2,
                            AlignmentID = "3",
                            Class = "Warrior",
                            Health = "3",
                            Intelligence = "3",
                            Luck = "3",
                            PlayerImageID = "3",
                            PlayerName = "Rhiordan Tannick",
                            Stamina = "3",
                            Stealth = "3",
                            Strength = "3"
                        },
                        new
                        {
                            PlayerID = 3,
                            AlignmentID = "3",
                            Class = "Rogue",
                            Health = "3",
                            Intelligence = "3",
                            Luck = "3",
                            PlayerImageID = "3",
                            PlayerName = "Bevil Starling",
                            Stamina = "3",
                            Stealth = "3",
                            Strength = "3"
                        });
                });

            modelBuilder.Entity("ReadyPlayerOne.Models.PlayerImage", b =>
                {
                    b.Property<string>("PlayerImageID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerImageID");

                    b.ToTable("PlayerImages");

                    b.HasData(
                        new
                        {
                            PlayerImageID = "1",
                            Image = "BlondeElfMaleWarrior.jpg"
                        },
                        new
                        {
                            PlayerImageID = "2",
                            Image = "BlondeWarlock.jpg"
                        },
                        new
                        {
                            PlayerImageID = "3",
                            Image = "BlondeWitch.jpg"
                        },
                        new
                        {
                            PlayerImageID = "4",
                            Image = "DarkHairedPriestess.jpg"
                        },
                        new
                        {
                            PlayerImageID = "5",
                            Image = "ElfFemaleFighter.jpg"
                        },
                        new
                        {
                            PlayerImageID = "6",
                            Image = "FemaleSamuraiWarrior.jpg"
                        },
                        new
                        {
                            PlayerImageID = "7",
                            Image = "FemaleWarriorInSilverArmor.jpg"
                        },
                        new
                        {
                            PlayerImageID = "8",
                            Image = "FemaleWaterCreature.jpg"
                        },
                        new
                        {
                            PlayerImageID = "9",
                            Image = "GoldenArcher.jpg"
                        },
                        new
                        {
                            PlayerImageID = "10",
                            Image = "GreenFairy.jpg"
                        },
                        new
                        {
                            PlayerImageID = "11",
                            Image = "HumanBoyWithCloak.jpg"
                        },
                        new
                        {
                            PlayerImageID = "12",
                            Image = "HumanFemaleKnight.jpg"
                        },
                        new
                        {
                            PlayerImageID = "13",
                            Image = "HumanGirlWithCloak.jpg"
                        },
                        new
                        {
                            PlayerImageID = "14",
                            Image = "HumanMaleDruid.jpg"
                        },
                        new
                        {
                            PlayerImageID = "15",
                            Image = "MaleSeaCreature.jpg"
                        },
                        new
                        {
                            PlayerImageID = "16",
                            Image = "MaleWarriorInSilverArmor.jpg"
                        },
                        new
                        {
                            PlayerImageID = "17",
                            Image = "MaleWithFlowerCrown.jpg"
                        },
                        new
                        {
                            PlayerImageID = "18",
                            Image = "ManWithSkullArmor.jpg"
                        },
                        new
                        {
                            PlayerImageID = "19",
                            Image = "MermaidWithBlueHair.jpg"
                        },
                        new
                        {
                            PlayerImageID = "20",
                            Image = "OlderManHuman.jpg"
                        },
                        new
                        {
                            PlayerImageID = "21",
                            Image = "OlderManWarrior.jpg"
                        },
                        new
                        {
                            PlayerImageID = "22",
                            Image = "OldWomanMage.jpg"
                        },
                        new
                        {
                            PlayerImageID = "23",
                            Image = "OldWomanMage.jpg"
                        },
                        new
                        {
                            PlayerImageID = "24",
                            Image = "WomanWithWhiteHair.jpg"
                        },
                        new
                        {
                            PlayerImageID = "25",
                            Image = "YoungRogue.png"
                        });
                });

            modelBuilder.Entity("ReadyPlayerOne.Models.Player", b =>
                {
                    b.HasOne("ReadyPlayerOne.Models.Alignment", "Alignment")
                        .WithMany()
                        .HasForeignKey("AlignmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReadyPlayerOne.Models.PlayerImage", "PlayerImage")
                        .WithMany()
                        .HasForeignKey("PlayerImageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alignment");

                    b.Navigation("PlayerImage");
                });
#pragma warning restore 612, 618
        }
    }
}
